### PR TITLE
Support --interface option for sdk, jce

### PR DESCRIPTION
**Pull request by khanbu**
Support --interface option, enable it for encryption and decryption for now

### CODE REVIEW

**Comment by govardhanfortanix** [comment]
have we tested this with latest interface changes, if so can we get same run result? @khanbu

**Comment by khanbu** [comment]
> have we tested this with latest interface changes, if so can we get sample run result? @khanbu

Please find the results below:

Command: ./test-bench.sh run encryption --algorithm AES --keysize 128 --mode CBC --interface jce

[ENCRYPTION-AES-128-jce-5THREADS-30SECONDS-CBC-AGGREGATE.csv](https://github.com/fortanix/sdkms-performance-testbench/files/6707208/ENCRYPTION-AES-128-jce-5THREADS-30SECONDS-CBC-AGGREGATE.csv)

Command: ./test-bench.sh run encryption --algorithm AES --keysize 128 --mode CBC --interface sdk

[ENCRYPTION-AES-128-sdk-5THREADS-30SECONDS-CBC-AGGREGATE.csv](https://github.com/fortanix/sdkms-performance-testbench/files/6707218/ENCRYPTION-AES-128-sdk-5THREADS-30SECONDS-CBC-AGGREGATE.csv)

Command: ./test-bench.sh run decryption --algorithm AES --keysize 128 --mode CBC --interface jce

[DECRYPTION-AES-128-jce-5THREADS-30SECONDS-CBC-AGGREGATE.csv](https://github.com/fortanix/sdkms-performance-testbench/files/6707270/DECRYPTION-AES-128-jce-5THREADS-30SECONDS-CBC-AGGREGATE.csv)

Command:  ./test-bench.sh run decryption --algorithm AES --keysize 128 --mode CBC --interface sdk
[DECRYPTION-AES-128-sdk-5THREADS-30SECONDS-CBC-AGGREGATE (1).csv](https://github.com/fortanix/sdkms-performance-testbench/files/6707308/DECRYPTION-AES-128-sdk-5THREADS-30SECONDS-CBC-AGGREGATE.1.csv)

(When interface is not mentioned then default would be sdk as below)
Command:  ./test-bench.sh run decryption --algorithm AES --keysize 128 --mode CBC
[DECRYPTION-AES-128-sdk-5THREADS-30SECONDS-CBC-AGGREGATE.csv](https://github.com/fortanix/sdkms-performance-testbench/files/6707283/DECRYPTION-AES-128-sdk-5THREADS-30SECONDS-CBC-AGGREGATE.csv)

**Comment by govardhanfortanix** [comment]
Looks fine for me

**Review by vishwas-ftx — APPROVED** [review]

**Review by vishwas-ftx — COMMENTED** [review]
Please update Readme

**Review by vishwas-ftx — APPROVED** [review]

**Pull request merged**
